fail_fast: true
repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: uv run --no-sync black langchain_docling test
        pass_filenames: false
        language: system
        files: '\.py$'
      - id: isort
        name: isort
        entry: uv run --no-sync isort langchain_docling test
        pass_filenames: false
        language: system
        files: '\.py$'
      - id: autoflake
        name: autoflake
        entry: uv run --no-sync autoflake langchain_docling test
        pass_filenames: false
        language: system
        files: '\.py$'
      - id: mypy
        name: MyPy
        entry: uv run --no-sync mypy langchain_docling test
        pass_filenames: false
        language: system
        files: '\.py$'
      - id: flake8
        name: Flake8
        entry: uv run --no-sync flake8 langchain_docling
        pass_filenames: false
        language: system
        files: '\.py$'
      - id: pytest
        name: Pytest
        entry: uv run --no-sync pytest --cov=langchain_docling --cov-report=xml test
        pass_filenames: false
        language: system
        files: '\.py$'
      - id: nbqa_black
        name: nbQA Black
        entry: uv run --no-sync nbqa black examples/
        pass_filenames: false
        language: system
        files: '\.ipynb$'
      - id: nbqa_isort
        name: nbQA isort
        entry: uv run --no-sync nbqa isort examples/
        pass_filenames: false
        language: system
        files: '\.ipynb$'
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.8
    hooks:
      - id: uv-lock
